# File: azure-pipelines.yml
# Date: 1-Jul-2019 jdw

trigger:
- master

pr:
- master

schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python27:
      python.version: '2.7'
  maxParallel: 2


steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      addToPath: true
  - checkout: self
    submodules: true
  - script: which apt
    displayName: 'Installing OS dependencies'
  - script: apt-cache policy | grep http | awk '{print $2 $3}' | sort -u
    displayName: 'Checking for repos'
  - script: sudo apt-get install flex
    displayName: 'Install flex'
  - script: sudo apt-get install bison
    displayName: 'Install bison'
  - script: sudo apt-get install mariadb-server mariadb-client
    displayName: 'Install mariadb'
  # Check the install
  - script: ls -lR .
    displayName: "Listing of installed software"
  #
  # Mongo install
  - script: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
    displayName: "Get MongoDb key"
  - script: sudo apt list --installed | grep mongodb
    displayName: "Check for installeed mongodb"
  - script: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
    displayName: "Install repo def"
  - script: sudo apt-get update
    displayName: "Reload package data"
  - script: sudo apt-get install -y mongodb-org
    displayName: "Install MongoDb package"
  - script:  sudo service mongod start
    displayName: "Start Mongo service"
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'

  - script: python -m pip install --upgrade pip
    displayName: 'Install tools'

  - script: pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: pip install tox
    displayName: 'Install Tox'

  - script: tox -v
    displayName: 'Run Tox'
